# Generated by Django 4.2.16 on 2024-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_plaform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiredata',
            name='alerts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tiredata',
            name='current_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tiredata',
            name='quantity_to_fill',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tiredata',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
