# Generated by Django 4.2.16 on 2024-11-19 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_plaform', '0002_alter_tiredata_alerts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlantasRecogidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_collected', models.IntegerField()),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llantas_recogidas', to='admin_plaform.container')),
                ('tire_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llantas_recogidas', to='admin_plaform.tiredata')),
            ],
        ),
    ]
