# Generated by Django 4.2.16 on 2024-11-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_plaform', '0003_llantasrecogidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiredata',
            name='quantity_ml',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
